[project]
site_name = "EduBehaviors-Kit"
site_url = "https://scale-nssa.github.io/edubehaviors-kit/"
repo_url = "https://github.com/scale-nssa/edubehaviors-kit"
repo_name = "scale-nssa/edubehaviors-kit"

nav = [
    { "Home" = "index.md" },
    { "Installation" = "installation.md" },
    { "Usage" = "usage.md" },
    { "Assertions" = "assertions.md" },
    { "Words" = "words.md" },
    { "API Reference" = "api.md" },
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "material/brightness-7"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to light mode"

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]
